
project_id = "qpdztqtszfvukqoiwsxu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions]
include_tables = ["public.addresses"]
